### ISSUE TITLE
Suggestion compatibility plot.radviz with ggplotly 

### ISSUE THREAD

**Issue by Laurevs** [yannabraham/Radviz#20]
Radviz version 0.9.2

I noticed the default label.size of the `plot.radviz` function is `NULL`, however for a standard ggplot the labels will still be printed. When creating an interactive plot using the ggplotly wrapper, labels will not be printed any more without specifically specifying the `label.size` argument. This might be confusing for the user. 
Potentially one could consider to give the `label.size` argument a different default value, to elaborate in the documentation/vignette or to directly implement an interactive function in the radviz package.

**Comment by yannabraham** [comment]
Looks like there is a sensible way to get the current default ggplot2 size, will implement it in the next release

**Comment by yannabraham** [comment]
should be fixed by d28f675071b926a7b5ae531d5ac7ea09080b10f7 - the `plot.radviz` function now uses the default ggplot2 text size rather than NA
